config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :users do
    resources :todoitems
  end
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todoitem.rb
class Todoitem < ApplicationRecord
	belongs_to :user
    validates :description, presence: true
    validates :status, inclusion: { in: %w(done created),
    message: "status only accept done or created" }

    validate :date_cannot_be_in_the_past,
    :due_time_cannot_earlier_than_the_date
 
	  def date_cannot_be_in_the_past
	    if date.present? && date < Date.today
	      errors.add(:date, "can't be in the past")
	    end
	  end
	 
	  def due_time_cannot_earlier_than_the_date
	    if due_time < date
	      errors.add(:due_time, "should no earlier than the date")
	    end
	  end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :todoitems
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, format: { with: /\A^(?=.*?[a-z])(?=.*?[0-9]).{6,}$\z/,
    message: "no shorter than 6 character’s, password containing at least one number, one lowercase letter" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if !user
      flash.now[:alert] = "Email is invalid"
      render "new"
    elsif user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    elsif !user.authenticate(params[:password])
      flash.now[:alert] = "Password is invalid"
      render "new"
    else
      
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/todoitems_controller.rb
class TodoitemsController < ApplicationController
  before_action :set_todoitem, only: [:show, :edit, :update, :destroy]

  # GET /todoitems
  # GET /todoitems.json
  def index
    @todoitems = Todoitem.all
  end

  # GET /todoitems/1
  # GET /todoitems/1.json
  def show
  end

  # GET /todoitems/new
  def new
    @todoitem = Todoitem.new
  end

  # GET /todoitems/1/edit
  def edit
  end

  # POST /todoitems
  # POST /todoitems.json
  def create
    @user = User.find(params[:user_id])
    @todoitem = @user.todoitems.create(todoitem_params)
    if @todoitem && @todoitem.save
      redirect_to user_path(@user), notice: 'successfully!!!'
    else
      redirect_to user_path(@user), notice: 'Faiure!!! The reason is:' + @todoitem.errors.messages.to_s
    end
  end

  # PATCH/PUT /todoitems/1
  # PATCH/PUT /todoitems/1.json
  def update
    respond_to do |format|
      if @todoitem.update(todoitem_params)
        format.html { redirect_to @todoitem, notice: 'Todoitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @todoitem }
      else
        format.html { render :edit }
        format.json { render json: @todoitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todoitems/1
  # DELETE /todoitems/1.json
  def destroy
    @user = User.find(params[:user_id])
    @todoitem = @user.todoitems.find(params[:id])
    @todoitem.destroy
    redirect_to user_path(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todoitem
      @todoitem = Todoitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todoitem_params
      params.require(:todoitem).permit(:description, :date, :due_time, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todoitems_helper.rb
module TodoitemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome to Todo List Page</h1>
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %><br><br><br><br>
  <%= link_to "Show todolist", 'users/'+ current_user.id.to_s %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or 
  <%= link_to "Log In", login_path %>
<% end %>
<p id="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todoitems/_form.html.erb
<%= form_for([@user, @user.todoitems.build]) do |form| %>
  
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :due_time %>
    <%= form.date_select :due_time %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todoitems/_todoitem.html.erb
<br>
<p>
  <strong>Todo_desc:</strong>
  <%= todoitem.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= todoitem.date %>
</p>

<p>
  <strong>Due_time:</strong>
  <%= todoitem.due_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= todoitem.status %>
</p>

<p>
  <%= link_to 'Destroy Todoitem', [todoitem.user, todoitem],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

<br><br><br><br>

app/views/todoitems/edit.html.erb
<h1>Editing Todoitem</h1>

<%= render 'form', todoitem: @todoitem %>

<%= link_to 'Show', @todoitem %> |
<%= link_to 'Back', todoitems_path %>

app/views/todoitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todoitems</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Date</th>
      <th>Due time</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todoitems.each do |todoitem| %>
      <tr>
        <td><%= todoitem.description %></td>
        <td><%= todoitem.date %></td>
        <td><%= todoitem.due_time %></td>
        <td><%= todoitem.status %></td>
        <td><%= link_to 'Show', todoitem %></td>
        <td><%= link_to 'Edit', edit_todoitem_path(todoitem) %></td>
        <td><%= link_to 'Destroy', todoitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todoitem', new_todoitem_path %>

app/views/todoitems/new.html.erb
<h1>New Todoitem</h1>

<%= render 'form', todoitem: @todoitem %>

<%= link_to 'Back', todoitems_path %>

app/views/todoitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @todoitem.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @todoitem.date %>
</p>

<p>
  <strong>Due time:</strong>
  <%= @todoitem.due_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todoitem.status %>
</p>

<%= link_to 'Edit', edit_todoitem_path(@todoitem) %> |
<%= link_to 'Back', todoitems_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_url %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_url %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.email %>
</p><br>
<%= link_to 'Change Pwd', edit_user_path(@user) %> |
<%= link_to 'Home page', root_url %>

<br><br>
<h2>Todo List</h2>
<%= render @user.todoitems %>
<br>
<h4>Add a todoitem:</h4>
<%= render 'todoitems/form' %>